# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, cmdargs, filepath, text, unorderedContainers,
  split
}:

cabal.mkDerivation (self: {
  pname = "devsurf";
  version = "0.0.1.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    attoparsec cmdargs filepath text unorderedContainers split
  ];
  meta = {
    homepage = "http://github.com/michelk/devsurf";
    description = "A developable surface design language";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
